<?php

require_once __DIR__ . '/fpdf19/fpdf.php';

class PdfGenerator extends FPDF {

    const REPORTS_DIR = 'C:/xampp/htdocs/crewsync/reports/';
    const REPORTS_URL = 'http://127.0.0.1/crewsync/reports/';

    private $title = '';

    public function __construct() {
        parent::__construct('P', 'mm', 'A4');
    }

    // ── DOCUMENT HEADER / FOOTER ──────────────────────────────────────────────
    public function Header() {
        if (!$this->title) return;
        $this->SetFont('Helvetica', 'B', 10);
        $this->SetTextColor(232, 130, 12);
        $this->Cell(0, 8, 'CREWSYNC', 0, 1, 'L');
        $this->SetFont('Helvetica', '', 8);
        $this->SetTextColor(138, 143, 168);
        $this->Cell(0, 5, $this->title, 0, 1, 'L');
        $this->SetTextColor(26, 29, 35);
        $this->SetDrawColor(222, 224, 230);
        $this->Line(10, $this->GetY() + 2, 200, $this->GetY() + 2);
        $this->SetY($this->GetY() + 4);
    }

    public function Footer() {
        $this->SetY(-15);
        $this->SetFont('Helvetica', 'I', 8);
        $this->SetTextColor(138, 143, 168);
        $this->Cell(0, 10, 'Generated by CrewSync  |  Page ' . $this->PageNo() . '/{nb}', 0, 0, 'C');
    }

    // ── SHARED BUILDING BLOCKS ────────────────────────────────────────────────
    private function sectionTitle($text) {
        $this->SetFont('Helvetica', 'B', 12);
        $this->SetTextColor(26, 29, 35);
        $this->Ln(4);
        $this->Cell(0, 8, $text, 0, 1, 'L');
        $this->SetTextColor(74, 80, 104);
        $this->SetFont('Helvetica', '', 9);
        $this->SetDrawColor(222, 224, 230);
        $this->Line(10, $this->GetY() + 1, 200, $this->GetY() + 1);
        $this->Ln(3);
    }

    private function labelRow($label, $value, $valueColor = [26, 29, 35]) {
        $this->SetFont('Helvetica', 'B', 9);
        $this->SetTextColor(138, 143, 168);
        $this->Cell(55, 6, $label, 0, 0, 'L');
        $this->SetFont('Helvetica', '', 9);
        $this->SetTextColor($valueColor[0], $valueColor[1], $valueColor[2]);
        $this->Cell(0, 6, $value, 0, 1, 'L');
        $this->SetTextColor(26, 29, 35);
    }

    private function keyValueTable($rows) {
        foreach ($rows as $label => $value) {
            $color = [26, 29, 35];
            if (is_array($value) && isset($value['color'])) {
                $color = $value['color'];
                $value = $value['text'];
            }
            $this->labelRow($label, (string) $value, $color);
        }
    }

    private function headerRow($cols) {
        $this->SetFillColor(247, 246, 242);
        $this->SetFont('Helvetica', 'B', 9);
        $this->SetTextColor(26, 29, 35);
        $this->SetDrawColor(222, 224, 230);
        foreach ($cols as $w => $label) {
            $this->Cell($w, 7, $label, 'B', 0, 'L', true);
        }
        $this->Ln();
    }

    private function bodyRow($cols, $aligns = []) {
        $this->SetFont('Helvetica', '', 9);
        $this->SetTextColor(26, 29, 35);
        foreach ($cols as $i => $text) {
            $align = $aligns[$i] ?? 'L';
            $this->Cell(array_keys($cols)[$i], 7, (string) $text, 'B', 0, $align);
        }
        $this->Ln();
    }

    private function amountColor($diff) {
        if ($diff > 0.005) return [194, 57, 43];
        if ($diff < -0.005) return [34, 145, 88];
        return [26, 29, 35];
    }

    private function money($amount) {
        return 'LKR ' . number_format((float) $amount, 2);
    }

    // ── TASK REPORT ───────────────────────────────────────────────────────────
    public function taskReport($facts) {
        $task   = $facts['task'];
        $title  = 'Task Report';
        $this->title = $title;
        $this->AliasNbPages();
        $this->AddPage();

        $this->SetFont('Helvetica', 'B', 16);
        $this->SetTextColor(26, 29, 35);
        $this->Cell(0, 9, $task['task_name'] ?? 'Task Report', 0, 1, 'L');

        $this->SetFont('Helvetica', '', 10);
        $this->SetTextColor(138, 143, 168);
        $this->Cell(0, 6, $task['project_name'] ?? 'Project Report', 0, 1, 'L');
        $this->Ln(4);

        $this->sectionTitle('Task Details');
        $this->keyValueTable([
            'Task Name'   => $task['task_name'] ?? '—',
            'Start Date'  => $task['start_date'] ?? '—',
            'End Date'    => $task['end_date'] ?? '—',
            'Worked Days' => $facts['worked_days'] . ' days',
            'Done By'     => $facts['providers'] ? implode(', ', $facts['providers']) : 'No Service providers were allocated',
        ]);

        $this->sectionTitle('Budget & Cost');
        $diff = $facts['diff'];
        $this->keyValueTable([
            'Budget'    => $this->money($facts['budget']),
            'Actual Cost' => $this->money($facts['cost']),
            'Difference'  => [
                'text'  => $this->money(abs($diff)) . ($diff > 0.005 ? ' exceeded' : ($diff < -0.005 ? ' saved' : ' on budget')),
                'color' => $this->amountColor($diff),
            ],
        ]);

        return $this->outputFile('task_' . $task['task_id'] . '_report');
    }

    // ── PROJECT REPORT ────────────────────────────────────────────────────────
    public function projectReport($facts) {
        $project = $facts['project'];
        $title   = 'Full Project Completion Report';
        $this->title = $title;
        $this->AliasNbPages();
        $this->AddPage();

        $this->SetFont('Helvetica', 'B', 16);
        $this->SetTextColor(26, 29, 35);
        $this->Cell(0, 9, $project['project_name'] ?? 'Project Completion Report', 0, 1, 'L');

        $this->SetFont('Helvetica', '', 10);
        $this->SetTextColor(138, 143, 168);
        $this->Cell(0, 6, $title, 0, 1, 'L');
        $this->Ln(4);

        $this->sectionTitle('Project Summary');
        $this->keyValueTable([
            'Project Name'  => $project['project_name'] ?? '—',
            'Start Date'    => $project['start_date'] ?? '—',
            'End Date'      => $project['end_date'] ?? '—',
            'Duration'      => ($facts['duration_days'] !== null ? $facts['duration_days'] . ' days' : '—'),
            'Tasks'         => count($facts['tasks']) . ' task(s)',
            'Total Worked'  => $facts['total_worked'] . ' days',
        ]);

        $this->sectionTitle('Budget & Cost');
        $diff = $facts['diff'];
        $this->keyValueTable([
            'Budget'      => $this->money($facts['budget']),
            'Actual Cost' => $this->money($facts['cost']),
            'Difference'  => [
                'text'  => $this->money(abs($diff)) . ($diff > 0.005 ? ' exceeded' : ($diff < -0.005 ? ' saved' : ' on budget')),
                'color' => $this->amountColor($diff),
            ],
        ]);

        $this->sectionTitle('Task Breakdown');
        if (!$facts['tasks']) {
            $this->SetFont('Helvetica', '', 9);
            $this->SetTextColor(138, 143, 168);
            $this->Cell(0, 6, 'No tasks found for this project.', 0, 1, 'L');
        } else {
            $this->headerRow([62 => 'Task', 38 => 'Worked', 50 => 'Budget', 50 => 'Cost']);
            foreach ($facts['tasks'] as $d) {
                $this->bodyRow(
                    [
                        $d['task']['task_name'] ?? '—',
                        ($d['worked_days']) . ' day(s)',
                        $this->money($d['budget']),
                        $this->money($d['cost']),
                    ],
                    ['L', 'C', 'R', 'R']
                );
            }
        }

        return $this->outputFile('project_' . $project['project_id'] . '_report');
    }

    // ── SAVE & RETURN URL ─────────────────────────────────────────────────────
    private function outputFile($prefix) {
        $filename = $prefix . '_' . date('Ymd_His') . '.pdf';
        $path     = self::REPORTS_DIR . $filename;
        $this->Output('F', $path);
        return self::REPORTS_URL . $filename;
    }
}
